# -*- coding: utf-8 -*-
"""arithmetic_mean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTVJSdcwgwfUDt8vauD15gG8FxYM61nc
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def apply_arithmetic_mean_filter(image, kernel_size):
    kernel = np.ones((kernel_size, kernel_size), dtype=np.float32) / (kernel_size * kernel_size)
    return cv2.filter2D(image, -1, kernel)

# Paths to images
image_path = '/content/drive/MyDrive/imageProcessing-nitw/Fig0507(b)(ckt-board-gauss-var-400).tif'
additional_image_path = '/content/drive/MyDrive/imageProcessing-nitw/Fig0507(a)(ckt-board-orig).tif'

# Read images
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
additional_image = cv2.imread(additional_image_path, cv2.IMREAD_GRAYSCALE)

# Check if images are loaded
if image is None:
    print(f"Failed to load image from {image_path}")
elif additional_image is None:
    print(f"Failed to load image from {additional_image_path}")
else:
    # Apply arithmetic mean filter
    filtered_arithmetic_mean = apply_arithmetic_mean_filter(image, 3)

    # Display images
    plt.figure(figsize=(16, 4))
    plt.subplot(1, 4, 1)
    plt.imshow(additional_image, cmap='gray')
    plt.title('original Image')
    plt.axis('off')
    plt.subplot(1, 4, 2)
    plt.imshow(image, cmap='gray')
    plt.title('Gaussian Noise')
    plt.axis('off')

    plt.subplot(1, 4, 3)
    plt.imshow(filtered_arithmetic_mean, cmap='gray')
    plt.title('Arithmetic Mean Filter (3x3)')
    plt.axis('off')



    plt.tight_layout()
    plt.show()

